---
name: Linting

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v5
      - name: Running YAMLlint
        uses: ibiqlik/action-yamllint@v3
        continue-on-error: false
        with:
          config_file: .github/yamllint-config.yml
  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v5
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: false
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."
