---
name: YAML Lint

'on':
  pull_request:
    branches: [master, main]
    paths:
      - '**.yml'
      - '**.yaml'
  push:
    branches: [master, main]
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Create yamllint config
        run: |
          cat > .yamllint.yml << EOF
          extends: default

          rules:
            # Allow longer lines for readability
            line-length:
              max: 120

            # Allow truthy values (yes/no, on/off, etc.)
            truthy:
              allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

            # Allow comments to exceed line length
            comments:
              min-spaces-from-content: 1
          EOF

      - name: Lint YAML files
        run: |
          # Find all YAML files and lint them
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) \
            -not -path "./.git/*" | xargs yamllint -c .yamllint.yml

      - name: List checked files
        run: |
          echo "The following YAML files were checked:"
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) \
            -not -path "./.git/*"
